#!/usr/bin/env php
<?php

$paths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../../../autoload.php',
];

foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}


use Imarc\Crawler\Commands\CsvCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputOption;

$application = new Application('Imarc Crawler');

$application->getDefinition()->addOptions([
    new InputOption('--http-username', null, InputOption::VALUE_OPTIONAL, 'HTTP basic auth username', null),
    new InputOption('--http-password', null, InputOption::VALUE_OPTIONAL, 'HTTP basic auth password', null),
]);

// ... register commands
$application->add(new CsvCommand());

$application->run();
