#!/usr/bin/env php
<?php

$paths = [
    __DIR__ . '/vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../../autoload.php',
];

foreach ($paths as $path) {
    if (file_exists($path)) {
        require_once $path;
        break;
    }
}


use Symfony\Component\Console\Application;
use Imarc\Crawler\Commands\CsvCommand;

$application = new Application('Imarc Crawler');

// ... register commands
$application->add(new CsvCommand());

$application->run();
